spring.application.name=monitoramento-aquario

# ===============================
# SERVER
# ===============================

server.port=${PORT:8080}


# ===============================
# POSTGRESQL
# ===============================

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/aquario}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}

spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.format_sql=true


# ===============================
# API KEY
# ===============================

aquario.api-key=${AQUARIO_API_KEY:meuaquariodepeixeestasendomonitorado}